// flow-typed signature: 6a3c4cb428a4b618eba9ffe6b3fd5c38
// flow-typed version: <<STUB>>/array-most-common_v^1.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-most-common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-most-common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'array-most-common/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'array-most-common/index' {
  declare module.exports: $Exports<'array-most-common'>;
}
declare module 'array-most-common/index.js' {
  declare module.exports: $Exports<'array-most-common'>;
}
declare module 'array-most-common/index.test.js' {
  declare module.exports: $Exports<'array-most-common/index.test'>;
}
