// flow-typed signature: f90ac740fae3f86d8c31ab4b035d69f1
// flow-typed version: <<STUB>>/canvas-fit_v^1.5.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canvas-fit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canvas-fit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canvas-fit/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canvas-fit/index' {
  declare module.exports: $Exports<'canvas-fit'>;
}
declare module 'canvas-fit/index.js' {
  declare module.exports: $Exports<'canvas-fit'>;
}
declare module 'canvas-fit/test.js' {
  declare module.exports: $Exports<'canvas-fit/test'>;
}
