// flow-typed signature: 731575cb563a4e1e511dd33147ba1d1a
// flow-typed version: <<STUB>>/clean-set_v^1.1.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-set' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clean-set/dist/clean-set.es' {
  declare module.exports: any;
}

declare module 'clean-set/dist/clean-set' {
  declare module.exports: any;
}

declare module 'clean-set/dist/clean-set.min' {
  declare module.exports: any;
}

declare module 'clean-set/lib/index' {
  declare module.exports: any;
}

declare module 'clean-set/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clean-set/dist/clean-set.es.js' {
  declare module.exports: $Exports<'clean-set/dist/clean-set.es'>;
}
declare module 'clean-set/dist/clean-set.js' {
  declare module.exports: $Exports<'clean-set/dist/clean-set'>;
}
declare module 'clean-set/dist/clean-set.min.js' {
  declare module.exports: $Exports<'clean-set/dist/clean-set.min'>;
}
declare module 'clean-set/lib/index.js' {
  declare module.exports: $Exports<'clean-set/lib/index'>;
}
declare module 'clean-set/tests/index.js' {
  declare module.exports: $Exports<'clean-set/tests/index'>;
}
