// flow-typed signature: a3f10b9cc8d3712ae7ed2e6258a44c8b
// flow-typed version: <<STUB>>/datauri-download_v^0.1.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'datauri-download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'datauri-download' {
  declare module.exports: (
    filename: string,
    type: string,
    data: string,
  ) => void;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'datauri-download/index' {
  declare module.exports: $Exports<'datauri-download'>;
}
declare module 'datauri-download/index.js' {
  declare module.exports: $Exports<'datauri-download'>;
}
