// flow-typed signature: 9abf4c48c6bcc7eb432a041d86c2fe31
// flow-typed version: <<STUB>>/filter-obj_v^1.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'filter-obj'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'filter-obj' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'filter-obj/index' {
  declare module.exports: $Exports<'filter-obj'>;
}
declare module 'filter-obj/index.js' {
  declare module.exports: $Exports<'filter-obj'>;
}
