// flow-typed signature: 11f5db37f1c7b9dd50ab9e625c41ce19
// flow-typed version: <<STUB>>/got_v^9.2.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'got'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'got' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'got/source/as-promise' {
  declare module.exports: any;
}

declare module 'got/source/as-stream' {
  declare module.exports: any;
}

declare module 'got/source/create' {
  declare module.exports: any;
}

declare module 'got/source/deep-freeze' {
  declare module.exports: any;
}

declare module 'got/source/errors' {
  declare module.exports: any;
}

declare module 'got/source/get-body-size' {
  declare module.exports: any;
}

declare module 'got/source/get-response' {
  declare module.exports: any;
}

declare module 'got/source/index' {
  declare module.exports: any;
}

declare module 'got/source/is-form-data' {
  declare module.exports: any;
}

declare module 'got/source/is-retry-on-network-error-allowed' {
  declare module.exports: any;
}

declare module 'got/source/known-hook-events' {
  declare module.exports: any;
}

declare module 'got/source/merge' {
  declare module.exports: any;
}

declare module 'got/source/normalize-arguments' {
  declare module.exports: any;
}

declare module 'got/source/progress' {
  declare module.exports: any;
}

declare module 'got/source/request-as-event-emitter' {
  declare module.exports: any;
}

declare module 'got/source/timed-out' {
  declare module.exports: any;
}

declare module 'got/source/url-to-options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'got/source/as-promise.js' {
  declare module.exports: $Exports<'got/source/as-promise'>;
}
declare module 'got/source/as-stream.js' {
  declare module.exports: $Exports<'got/source/as-stream'>;
}
declare module 'got/source/create.js' {
  declare module.exports: $Exports<'got/source/create'>;
}
declare module 'got/source/deep-freeze.js' {
  declare module.exports: $Exports<'got/source/deep-freeze'>;
}
declare module 'got/source/errors.js' {
  declare module.exports: $Exports<'got/source/errors'>;
}
declare module 'got/source/get-body-size.js' {
  declare module.exports: $Exports<'got/source/get-body-size'>;
}
declare module 'got/source/get-response.js' {
  declare module.exports: $Exports<'got/source/get-response'>;
}
declare module 'got/source/index.js' {
  declare module.exports: $Exports<'got/source/index'>;
}
declare module 'got/source/is-form-data.js' {
  declare module.exports: $Exports<'got/source/is-form-data'>;
}
declare module 'got/source/is-retry-on-network-error-allowed.js' {
  declare module.exports: $Exports<'got/source/is-retry-on-network-error-allowed'>;
}
declare module 'got/source/known-hook-events.js' {
  declare module.exports: $Exports<'got/source/known-hook-events'>;
}
declare module 'got/source/merge.js' {
  declare module.exports: $Exports<'got/source/merge'>;
}
declare module 'got/source/normalize-arguments.js' {
  declare module.exports: $Exports<'got/source/normalize-arguments'>;
}
declare module 'got/source/progress.js' {
  declare module.exports: $Exports<'got/source/progress'>;
}
declare module 'got/source/request-as-event-emitter.js' {
  declare module.exports: $Exports<'got/source/request-as-event-emitter'>;
}
declare module 'got/source/timed-out.js' {
  declare module.exports: $Exports<'got/source/timed-out'>;
}
declare module 'got/source/url-to-options.js' {
  declare module.exports: $Exports<'got/source/url-to-options'>;
}
