// flow-typed signature: 696097eea6444dddc1b0ac80489f6b46
// flow-typed version: <<STUB>>/hibiscss_v0.0.9/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hibiscss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hibiscss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hibiscss/default' {
  declare module.exports: any;
}

declare module 'hibiscss/examples/basic' {
  declare module.exports: any;
}

declare module 'hibiscss/examples/custom-kit' {
  declare module.exports: any;
}

declare module 'hibiscss/examples/tachyons' {
  declare module.exports: any;
}

declare module 'hibiscss/lib/index' {
  declare module.exports: any;
}

declare module 'hibiscss/lib/rule' {
  declare module.exports: any;
}

declare module 'hibiscss/lib/stylesheet' {
  declare module.exports: any;
}

declare module 'hibiscss/src/index' {
  declare module.exports: any;
}

declare module 'hibiscss/src/rule' {
  declare module.exports: any;
}

declare module 'hibiscss/src/rule.test' {
  declare module.exports: any;
}

declare module 'hibiscss/src/stylesheet' {
  declare module.exports: any;
}

declare module 'hibiscss/src/stylesheet.test' {
  declare module.exports: any;
}

declare module 'hibiscss/src/types' {
  declare module.exports: any;
}

declare module 'hibiscss/tachyons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hibiscss/default.js' {
  declare module.exports: $Exports<'hibiscss/default'>;
}
declare module 'hibiscss/examples/basic.js' {
  declare module.exports: $Exports<'hibiscss/examples/basic'>;
}
declare module 'hibiscss/examples/custom-kit.js' {
  declare module.exports: $Exports<'hibiscss/examples/custom-kit'>;
}
declare module 'hibiscss/examples/tachyons.js' {
  declare module.exports: $Exports<'hibiscss/examples/tachyons'>;
}
declare module 'hibiscss/lib/index.js' {
  declare module.exports: $Exports<'hibiscss/lib/index'>;
}
declare module 'hibiscss/lib/rule.js' {
  declare module.exports: $Exports<'hibiscss/lib/rule'>;
}
declare module 'hibiscss/lib/stylesheet.js' {
  declare module.exports: $Exports<'hibiscss/lib/stylesheet'>;
}
declare module 'hibiscss/src/index.js' {
  declare module.exports: $Exports<'hibiscss/src/index'>;
}
declare module 'hibiscss/src/rule.js' {
  declare module.exports: $Exports<'hibiscss/src/rule'>;
}
declare module 'hibiscss/src/rule.test.js' {
  declare module.exports: $Exports<'hibiscss/src/rule.test'>;
}
declare module 'hibiscss/src/stylesheet.js' {
  declare module.exports: $Exports<'hibiscss/src/stylesheet'>;
}
declare module 'hibiscss/src/stylesheet.test.js' {
  declare module.exports: $Exports<'hibiscss/src/stylesheet.test'>;
}
declare module 'hibiscss/src/types.js' {
  declare module.exports: $Exports<'hibiscss/src/types'>;
}
declare module 'hibiscss/tachyons.js' {
  declare module.exports: $Exports<'hibiscss/tachyons'>;
}
