// flow-typed signature: 55beeb6b3613f768385568f6bf3920c3
// flow-typed version: <<STUB>>/milliseconds_v^1.0.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'milliseconds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'milliseconds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'milliseconds/milliseconds' {
  declare module.exports: any;
}

declare module 'milliseconds/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'milliseconds/milliseconds.js' {
  declare module.exports: $Exports<'milliseconds/milliseconds'>;
}
declare module 'milliseconds/test.js' {
  declare module.exports: $Exports<'milliseconds/test'>;
}
