// flow-typed signature: 12e58cf94e3264ae64065efc5b8c227f
// flow-typed version: <<STUB>>/money-clip_v^2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'money-clip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'money-clip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'money-clip/dist/money-clip' {
  declare module.exports: any;
}

declare module 'money-clip/dist/money-clip.m' {
  declare module.exports: any;
}

declare module 'money-clip/dist/money-clip.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'money-clip/dist/money-clip.js' {
  declare module.exports: $Exports<'money-clip/dist/money-clip'>;
}
declare module 'money-clip/dist/money-clip.m.js' {
  declare module.exports: $Exports<'money-clip/dist/money-clip.m'>;
}
declare module 'money-clip/dist/money-clip.umd.js' {
  declare module.exports: $Exports<'money-clip/dist/money-clip.umd'>;
}
