// flow-typed signature: c37a47849250d37a7068af64c55772e5
// flow-typed version: <<STUB>>/mongorito_v^3.0.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongorito'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongorito' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongorito/lib/action-types' {
  declare module.exports: any;
}

declare module 'mongorito/lib/actions' {
  declare module.exports: any;
}

declare module 'mongorito/lib/create-store' {
  declare module.exports: any;
}

declare module 'mongorito/lib/database' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/call' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/create-index' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/create' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/drop-index' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/get' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/increment' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/list-indexes' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/query' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/refresh' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/remove' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/save' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/set' {
  declare module.exports: any;
}

declare module 'mongorito/lib/middleware/update' {
  declare module.exports: any;
}

declare module 'mongorito/lib/model' {
  declare module.exports: any;
}

declare module 'mongorito/lib/query-methods' {
  declare module.exports: any;
}

declare module 'mongorito/lib/query' {
  declare module.exports: any;
}

declare module 'mongorito/lib/reducers/fields' {
  declare module.exports: any;
}

declare module 'mongorito/lib/reducers/unset-fields' {
  declare module.exports: any;
}

declare module 'mongorito/lib/serialize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongorito/index' {
  declare module.exports: $Exports<'mongorito'>;
}
declare module 'mongorito/index.js' {
  declare module.exports: $Exports<'mongorito'>;
}
declare module 'mongorito/lib/action-types.js' {
  declare module.exports: $Exports<'mongorito/lib/action-types'>;
}
declare module 'mongorito/lib/actions.js' {
  declare module.exports: $Exports<'mongorito/lib/actions'>;
}
declare module 'mongorito/lib/create-store.js' {
  declare module.exports: $Exports<'mongorito/lib/create-store'>;
}
declare module 'mongorito/lib/database.js' {
  declare module.exports: $Exports<'mongorito/lib/database'>;
}
declare module 'mongorito/lib/middleware/call.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/call'>;
}
declare module 'mongorito/lib/middleware/create-index.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/create-index'>;
}
declare module 'mongorito/lib/middleware/create.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/create'>;
}
declare module 'mongorito/lib/middleware/drop-index.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/drop-index'>;
}
declare module 'mongorito/lib/middleware/get.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/get'>;
}
declare module 'mongorito/lib/middleware/increment.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/increment'>;
}
declare module 'mongorito/lib/middleware/list-indexes.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/list-indexes'>;
}
declare module 'mongorito/lib/middleware/query.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/query'>;
}
declare module 'mongorito/lib/middleware/refresh.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/refresh'>;
}
declare module 'mongorito/lib/middleware/remove.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/remove'>;
}
declare module 'mongorito/lib/middleware/save.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/save'>;
}
declare module 'mongorito/lib/middleware/set.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/set'>;
}
declare module 'mongorito/lib/middleware/update.js' {
  declare module.exports: $Exports<'mongorito/lib/middleware/update'>;
}
declare module 'mongorito/lib/model.js' {
  declare module.exports: $Exports<'mongorito/lib/model'>;
}
declare module 'mongorito/lib/query-methods.js' {
  declare module.exports: $Exports<'mongorito/lib/query-methods'>;
}
declare module 'mongorito/lib/query.js' {
  declare module.exports: $Exports<'mongorito/lib/query'>;
}
declare module 'mongorito/lib/reducers/fields.js' {
  declare module.exports: $Exports<'mongorito/lib/reducers/fields'>;
}
declare module 'mongorito/lib/reducers/unset-fields.js' {
  declare module.exports: $Exports<'mongorito/lib/reducers/unset-fields'>;
}
declare module 'mongorito/lib/serialize.js' {
  declare module.exports: $Exports<'mongorito/lib/serialize'>;
}
