// flow-typed signature: 8fa22c9b024978c60cc8d7b4a260d6f0
// flow-typed version: <<STUB>>/noisejs_v^2.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'noisejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'noisejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'noisejs/index' {
  declare module.exports: $Exports<'noisejs'>;
}
declare module 'noisejs/index.js' {
  declare module.exports: $Exports<'noisejs'>;
}
