// flow-typed signature: ed7efe1e6e0612ffbda867b9c982a86c
// flow-typed version: <<STUB>>/p-map_v^1.2.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-map/index' {
  declare module.exports: $Exports<'p-map'>;
}
declare module 'p-map/index.js' {
  declare module.exports: $Exports<'p-map'>;
}
