// flow-typed signature: daa97a6b11e76dc688accb5ce6105457
// flow-typed version: <<STUB>>/poketo_v^0.2.5/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'poketo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'poketo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'poketo/lib/adapters/helvetica-scans' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/hot-chocolate-scans' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/index' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/jaiminis-box' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/kirei-cake' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/manga-here' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/manga-rock' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/manga-stream' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/manga-updates' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/mangadex' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/mangakakalot' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/manganelo' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/meraki-scans' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/phoenix-serenade' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/sen-manga' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/sense-scans' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/shared/fool-slide' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/shared/mangakakalot' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/silent-sky-scans' {
  declare module.exports: any;
}

declare module 'poketo/lib/adapters/tuki-scans' {
  declare module.exports: any;
}

declare module 'poketo/lib/errors' {
  declare module.exports: any;
}

declare module 'poketo/lib/get' {
  declare module.exports: any;
}

declare module 'poketo/lib/index' {
  declare module.exports: any;
}

declare module 'poketo/lib/setup-tests' {
  declare module.exports: any;
}

declare module 'poketo/lib/utils' {
  declare module.exports: any;
}

declare module 'poketo/supports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'poketo/lib/adapters/helvetica-scans.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/helvetica-scans'>;
}
declare module 'poketo/lib/adapters/hot-chocolate-scans.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/hot-chocolate-scans'>;
}
declare module 'poketo/lib/adapters/index.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/index'>;
}
declare module 'poketo/lib/adapters/jaiminis-box.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/jaiminis-box'>;
}
declare module 'poketo/lib/adapters/kirei-cake.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/kirei-cake'>;
}
declare module 'poketo/lib/adapters/manga-here.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/manga-here'>;
}
declare module 'poketo/lib/adapters/manga-rock.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/manga-rock'>;
}
declare module 'poketo/lib/adapters/manga-stream.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/manga-stream'>;
}
declare module 'poketo/lib/adapters/manga-updates.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/manga-updates'>;
}
declare module 'poketo/lib/adapters/mangadex.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/mangadex'>;
}
declare module 'poketo/lib/adapters/mangakakalot.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/mangakakalot'>;
}
declare module 'poketo/lib/adapters/manganelo.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/manganelo'>;
}
declare module 'poketo/lib/adapters/meraki-scans.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/meraki-scans'>;
}
declare module 'poketo/lib/adapters/phoenix-serenade.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/phoenix-serenade'>;
}
declare module 'poketo/lib/adapters/sen-manga.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/sen-manga'>;
}
declare module 'poketo/lib/adapters/sense-scans.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/sense-scans'>;
}
declare module 'poketo/lib/adapters/shared/fool-slide.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/shared/fool-slide'>;
}
declare module 'poketo/lib/adapters/shared/mangakakalot.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/shared/mangakakalot'>;
}
declare module 'poketo/lib/adapters/silent-sky-scans.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/silent-sky-scans'>;
}
declare module 'poketo/lib/adapters/tuki-scans.js' {
  declare module.exports: $Exports<'poketo/lib/adapters/tuki-scans'>;
}
declare module 'poketo/lib/errors.js' {
  declare module.exports: $Exports<'poketo/lib/errors'>;
}
declare module 'poketo/lib/get.js' {
  declare module.exports: $Exports<'poketo/lib/get'>;
}
declare module 'poketo/lib/index.js' {
  declare module.exports: $Exports<'poketo/lib/index'>;
}
declare module 'poketo/lib/setup-tests.js' {
  declare module.exports: $Exports<'poketo/lib/setup-tests'>;
}
declare module 'poketo/lib/utils.js' {
  declare module.exports: $Exports<'poketo/lib/utils'>;
}
declare module 'poketo/supports.js' {
  declare module.exports: $Exports<'poketo/supports'>;
}
