// flow-typed signature: 50b6fdbb1b4abfc199ca48756659eeac
// flow-typed version: <<STUB>>/react-scrolllock_v^2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrolllock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrolllock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scrolllock/lib/constants' {
  declare module.exports: any;
}

declare module 'react-scrolllock/lib/index' {
  declare module.exports: any;
}

declare module 'react-scrolllock/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scrolllock/lib/constants.js' {
  declare module.exports: $Exports<'react-scrolllock/lib/constants'>;
}
declare module 'react-scrolllock/lib/index.js' {
  declare module.exports: $Exports<'react-scrolllock/lib/index'>;
}
declare module 'react-scrolllock/lib/utils.js' {
  declare module.exports: $Exports<'react-scrolllock/lib/utils'>;
}
