// flow-typed signature: 73b90768082fe888e7689a34e1e7bddf
// flow-typed version: <<STUB>>/react-textarea-autosize_v^6.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-textarea-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-textarea-autosize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.es' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.cjs'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.es.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.es'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.min.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.min'>;
}
