// flow-typed signature: fa72bf72abaed2a20b0a8aa854848088
// flow-typed version: <<STUB>>/react-scrolllock_v^2.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrolllock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrolllock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scrolllock/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-scrolllock/config/setupFramework' {
  declare module.exports: any;
}

declare module 'react-scrolllock/config/setupPolyfills' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/constants' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/index' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/PropertyToggle' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/ScrollLock' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/server' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/utils' {
  declare module.exports: any;
}

declare module 'react-scrolllock/dist/withTouchListeners' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scrolllock/__tests__/index.js' {
  declare module.exports: $Exports<'react-scrolllock/__tests__/index'>;
}
declare module 'react-scrolllock/config/setupFramework.js' {
  declare module.exports: $Exports<'react-scrolllock/config/setupFramework'>;
}
declare module 'react-scrolllock/config/setupPolyfills.js' {
  declare module.exports: $Exports<'react-scrolllock/config/setupPolyfills'>;
}
declare module 'react-scrolllock/dist/constants.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/constants'>;
}
declare module 'react-scrolllock/dist/index.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/index'>;
}
declare module 'react-scrolllock/dist/PropertyToggle.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/PropertyToggle'>;
}
declare module 'react-scrolllock/dist/ScrollLock.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/ScrollLock'>;
}
declare module 'react-scrolllock/dist/server.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/server'>;
}
declare module 'react-scrolllock/dist/utils.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/utils'>;
}
declare module 'react-scrolllock/dist/withTouchListeners.js' {
  declare module.exports: $Exports<'react-scrolllock/dist/withTouchListeners'>;
}
declare module 'react-scrolllock/index' {
  declare module.exports: $Exports<'react-scrolllock'>;
}
declare module 'react-scrolllock/index.js' {
  declare module.exports: $Exports<'react-scrolllock'>;
}
