// flow-typed signature: ac165b145c8d48b86a374d963cf19ab1
// flow-typed version: <<STUB>>/redux-persist-middleware_v^1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-middleware/dist/money-clip' {
  declare module.exports: any;
}

declare module 'redux-persist-middleware/dist/money-clip.m' {
  declare module.exports: any;
}

declare module 'redux-persist-middleware/dist/money-clip.umd' {
  declare module.exports: any;
}

declare module 'redux-persist-middleware/dist/redux-persist-middleware' {
  declare module.exports: any;
}

declare module 'redux-persist-middleware/dist/redux-persist-middleware.m' {
  declare module.exports: any;
}

declare module 'redux-persist-middleware/dist/redux-persist-middleware.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-middleware/dist/money-clip.js' {
  declare module.exports: $Exports<'redux-persist-middleware/dist/money-clip'>;
}
declare module 'redux-persist-middleware/dist/money-clip.m.js' {
  declare module.exports: $Exports<'redux-persist-middleware/dist/money-clip.m'>;
}
declare module 'redux-persist-middleware/dist/money-clip.umd.js' {
  declare module.exports: $Exports<'redux-persist-middleware/dist/money-clip.umd'>;
}
declare module 'redux-persist-middleware/dist/redux-persist-middleware.js' {
  declare module.exports: $Exports<'redux-persist-middleware/dist/redux-persist-middleware'>;
}
declare module 'redux-persist-middleware/dist/redux-persist-middleware.m.js' {
  declare module.exports: $Exports<'redux-persist-middleware/dist/redux-persist-middleware.m'>;
}
declare module 'redux-persist-middleware/dist/redux-persist-middleware.umd.js' {
  declare module.exports: $Exports<'redux-persist-middleware/dist/redux-persist-middleware.umd'>;
}
