// flow-typed signature: b2d412a4e7e4a412a94359ff14bbb118
// flow-typed version: <<STUB>>/s-ago_v^1.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   's-ago'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's-ago' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's-ago/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 's-ago/index' {
  declare module.exports: $Exports<'s-ago'>;
}
declare module 's-ago/index.js' {
  declare module.exports: $Exports<'s-ago'>;
}
declare module 's-ago/test/test.js' {
  declare module.exports: $Exports<'s-ago/test/test'>;
}
