// flow-typed signature: fe4d79b9ca129086a8548c76c04e2ebe
// flow-typed version: <<STUB>>/s-ago_v^1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's-ago'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's-ago' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's-ago/gulpfile' {
  declare module.exports: any;
}

declare module 's-ago/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 's-ago/gulpfile.js' {
  declare module.exports: $Exports<'s-ago/gulpfile'>;
}
declare module 's-ago/index' {
  declare module.exports: $Exports<'s-ago'>;
}
declare module 's-ago/index.js' {
  declare module.exports: $Exports<'s-ago'>;
}
declare module 's-ago/test/spec.js' {
  declare module.exports: $Exports<'s-ago/test/spec'>;
}
