// flow-typed signature: e10062cd4d88c095c86048b2efb07679
// flow-typed version: <<STUB>>/trae_v^1.4.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trae'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trae' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trae/dist/trae' {
  declare module.exports: any;
}

declare module 'trae/dist/trae.umd' {
  declare module.exports: any;
}

declare module 'trae/dist/trae.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trae/dist/trae.js' {
  declare module.exports: $Exports<'trae/dist/trae'>;
}
declare module 'trae/dist/trae.umd.js' {
  declare module.exports: $Exports<'trae/dist/trae.umd'>;
}
declare module 'trae/dist/trae.umd.min.js' {
  declare module.exports: $Exports<'trae/dist/trae.umd.min'>;
}
