// flow-typed signature: cd8f54de373251c4b8782ee3594b7985
// flow-typed version: <<STUB>>/@svgr/core_v^2.4.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/core/lib/config' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/convert' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/emSize' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/expandProps' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/removeComments' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/removeDimensions' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/removeStyle' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/replaceAttrValues' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/stripAttribute' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/svgAttributes' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/svgProps' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/svgRef' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/titleProp' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/h2x/toReactNative' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/index' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/plugins/h2x' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/plugins/prettier' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/plugins/svgo' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/plugins/transform' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/templates/reactDomTemplate' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/templates/reactNativeTemplate' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/templates/util' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/core/lib/config.js' {
  declare module.exports: $Exports<'@svgr/core/lib/config'>;
}
declare module '@svgr/core/lib/convert.js' {
  declare module.exports: $Exports<'@svgr/core/lib/convert'>;
}
declare module '@svgr/core/lib/h2x/emSize.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/emSize'>;
}
declare module '@svgr/core/lib/h2x/expandProps.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/expandProps'>;
}
declare module '@svgr/core/lib/h2x/removeComments.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/removeComments'>;
}
declare module '@svgr/core/lib/h2x/removeDimensions.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/removeDimensions'>;
}
declare module '@svgr/core/lib/h2x/removeStyle.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/removeStyle'>;
}
declare module '@svgr/core/lib/h2x/replaceAttrValues.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/replaceAttrValues'>;
}
declare module '@svgr/core/lib/h2x/stripAttribute.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/stripAttribute'>;
}
declare module '@svgr/core/lib/h2x/svgAttributes.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/svgAttributes'>;
}
declare module '@svgr/core/lib/h2x/svgProps.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/svgProps'>;
}
declare module '@svgr/core/lib/h2x/svgRef.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/svgRef'>;
}
declare module '@svgr/core/lib/h2x/titleProp.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/titleProp'>;
}
declare module '@svgr/core/lib/h2x/toReactNative.js' {
  declare module.exports: $Exports<'@svgr/core/lib/h2x/toReactNative'>;
}
declare module '@svgr/core/lib/index.js' {
  declare module.exports: $Exports<'@svgr/core/lib/index'>;
}
declare module '@svgr/core/lib/plugins/h2x.js' {
  declare module.exports: $Exports<'@svgr/core/lib/plugins/h2x'>;
}
declare module '@svgr/core/lib/plugins/prettier.js' {
  declare module.exports: $Exports<'@svgr/core/lib/plugins/prettier'>;
}
declare module '@svgr/core/lib/plugins/svgo.js' {
  declare module.exports: $Exports<'@svgr/core/lib/plugins/svgo'>;
}
declare module '@svgr/core/lib/plugins/transform.js' {
  declare module.exports: $Exports<'@svgr/core/lib/plugins/transform'>;
}
declare module '@svgr/core/lib/templates/reactDomTemplate.js' {
  declare module.exports: $Exports<'@svgr/core/lib/templates/reactDomTemplate'>;
}
declare module '@svgr/core/lib/templates/reactNativeTemplate.js' {
  declare module.exports: $Exports<'@svgr/core/lib/templates/reactNativeTemplate'>;
}
declare module '@svgr/core/lib/templates/util.js' {
  declare module.exports: $Exports<'@svgr/core/lib/templates/util'>;
}
declare module '@svgr/core/lib/util.js' {
  declare module.exports: $Exports<'@svgr/core/lib/util'>;
}
